/**
 ******************************************************************************
 * @file           : main.c
 * @author         : Auto-generated by STM32CubeIDE
 * @brief          : Main program body
 ******************************************************************************
 * @attention
 *
 * Copyright (c) 2024 STMicroelectronics.
 * All rights reserved.
 *
 * This software is licensed under terms that can be found in the LICENSE file
 * in the root directory of this software component.
 * If no LICENSE file comes with this software, it is provided AS-IS.
 *
 ******************************************************************************
 */
#include <stdint.h>

#define RCC_BASE_ADDR 0x40023800UL

#define RCC_CFGR_REG_OFFSET 0x08UL

#define RCC_CFGR_REG_ADDR (RCC_BASE_ADDR + RCC_CFGR_REG_OFFSET)

int main(void)
{
    //	uint32_t *pRccCfgrReg = (uint32_t *) RCC_CFGR_REG_ADDR;
    //
    //	//1. Configure the RCC_CFGR MCO1 bit fields to select HSI as clock source
    //	*pRccCfgrReg &= ~(0x3 << 21); //Clear 21 & 22 bit position
    //
    //	//2. Configure PA8 to AF0 mode to behave as MCO1 signal
    //
    //	// (a) Enable the peripheral clock for GPIOA peripheral
    //	uint32_t *pRCCAhb1End = (uint32_t *)(RCC_BASE_ADDR + 0x30);
    //	*pRCCAhb1End |= (1 << 0);
    //
    //	// (b) Configure the mode of GPIOA pin 8 as alternate function mode
    //	uint32_t *pGPIOAModeReg = (uint32_t*)(GPIOA_BASE_ADDR + 00);
    //	*pGPIOAModeReg &= ~(0x3 << 16); //clear
    //	*pGPIOAModeReg |= (0x2 << 16); //set
    //
    //	// (c) Configure the alternation function register to set the mode 0 for PA8
    //	*pGPIOAAltFunHighReg &= ~(0xF << 0);
}
